### ISSUE TITLE
コードの改良とサークル内での頒布について

### ISSUE THREAD

**Issue by HayatoHongo** [mkybdev/utol_mod_ts#1]
開発者様

初めまして。東京大学AI研究会の本郷と申します。突然のご連絡失礼いたします。

弊団体では毎週水曜日の6限に活動を行っており、このたび貴プロダクトの予定機能を活用させていただくことで、対面での勉強会の参加率向上を図れるのではないかと考えております。

現状では、オリジナルの予定を登録した際、その予定の時間割のコマをクリックしても詳細ページに遷移しない仕様かと存じます。弊会では現在、Google Driveを活用したオンラインでの受講管理や宿題の共有を行っておりますが、これをWebアプリとして運用し、そのリンクURLを「内容」部分に記載することを検討しております。さらに、ユーザー体験を向上させるため、コマをクリックすることで即座に該当URLへ遷移する機能があればと考えております。

つきましては、コードを一部改良し、弊サークル内（40名程度）で再頒布することについて、開発者様のご許可を賜りたくお願い申し上げます。

ご多忙のところ恐れ入りますが、ご検討のほど何卒よろしくお願い申し上げます。

敬具

東京大学AI研究会
本郷

**Comment by mkybdev** [comment]
本郷様、ご利用していただきありがとうございます。
予定機能の改良・再頒布についてはもちろん可能ですので、適宜進めていただければと思います。
また「**コマをクリックすることで即座に該当URLへ遷移する機能**」はぜひ実装したいと思いますので、差し支えなければ改良後にPRしていただければ幸いです。
よろしくお願いいたします。

**Comment by HayatoHongo** [comment]
開発者様

ありがとうございます。
どのくらい時間がかかるかはわかりませんが、完成次第、改良後のコードについても共有させていただきたいと思います。

本郷

**Comment by HayatoHongo** [comment]
開発者様

URLのリダイレクト機能を追加させていただきました。
https://github.com/HayatoHongo/utol_mod_ts_for_aiken

add_schedule.htmlとadd_schedule.tsにURLの入力部分を追加し、content.tsのShowScheduleDialogue関数に、urlが登録されていればリダイレクト、登録されていなければ従来通りとしました。

URLを登録した予定に関しては削除できなくなってしまったのですが、拡張機能を再インストールすればリセットできるのと、滅多に登録ミスはないだろう、、という憶測でとりあえず特に何もしていません。

TypeScriptに触るのが初めてで、特にtsファイルをjsファイルに変換するビルドの部分で手こずってしまったので、パッケージのzipファイルのフォルダ構造は元々のzipファイルとは異なっています。
https://github.com/HayatoHongo/utol_mod_ts_for_aiken/releases/download/v0/utol_mod_url.zip

ソースコード自体については前述の通りの変化しかないので、私のzipパッケージのフォルダ構造は気にせず、開発者様の環境でビルドしても問題はないかと思います。

ご厚意に感謝いたします。サークルでもしっかり活用させていただきます。

本郷

**Comment by mkybdev** [comment]
ありがとうございます。
諸事情あって全くTSの良さを活かせていないコードになっているのでプログラミングがしづらかったと思います、すみません。
もし可能であればプルリクエストの形でこちらのリポジトリに変更を取り込みたいですが、もし難しければこちらで本郷様のクレジット付きでコードを直接変更させていただきます。
よろしくお願いします。

**Comment by HayatoHongo** [comment]
プルリクエストの方を送信させていただきました。
ビルドに影響を与えるような変更をしていないとは思うのですが、若干その辺りがうろ覚えでして、プルリクエストに基づいて変更した後、開発者様の環境でビルドがうまく行かなかったら教えてください。

本郷
